use crate::data::map::generation::step::{get_attribute_id, GenerationStepError};
use crate::data::map::Map2d;
use crate::data::math::generator::generator2d::{Generator2d, Generator2dData};
use serde::{Deserialize, Serialize};
use std::convert::TryInto;

/// Modifies an [`Attribute`] with the values generated by a [`Generator2d`].
pub struct GeneratorStep {
    name: String,
    attribute_id: usize,
    generator: Generator2d,
}

impl GeneratorStep {
    pub fn new<S: Into<String>>(
        name: S,
        attribute_id: usize,
        generator: Generator2d,
    ) -> GeneratorStep {
        GeneratorStep {
            name: name.into(),
            attribute_id,
            generator,
        }
    }

    // Adds the values.
    ///
    /// ```
    ///# use ofws_core::data::map::Map2d;
    ///# use ofws_core::data::map::generation::attributes::generator::GeneratorStep;
    ///# use ofws_core::data::map::generation::step::GenerationStep;
    ///# use ofws_core::data::math::generator::generator2d::Generator2d::IndexGenerator;
    ///# use ofws_core::data::math::size2d::Size2d;
    /// let size = Size2d::new(2, 3);
    /// let mut map = Map2d::new(size);
    /// let attribute_id = map.create_attribute("elevation", 40).unwrap();
    /// let generator = IndexGenerator(size);
    /// let step = GeneratorStep::new("test", attribute_id,generator);
    ///
    /// step.add(&mut map);
    ///
    /// let attribute = map.get_attribute(attribute_id);
    /// assert_eq!(attribute.get_all(), &vec![40u8, 41, 42, 43, 44, 45]);
    /// ```
    pub fn add(&self, map: &mut Map2d) {
        info!(
            "Add '{}' to attribute '{}' of map '{}'",
            self.name,
            map.get_attribute(self.attribute_id).get_name(),
            map.get_name()
        );

        let size = map.size;
        let attribute = map.get_attribute_mut(self.attribute_id);
        let mut index = 0;

        for y in 0..size.height() {
            for x in 0..size.width() {
                let value = self.generator.generate(x, y);
                let sum = attribute.get(index).saturating_add(value);
                *attribute.get_mut(index) = sum;
                index += 1;
            }
        }
    }

    // Subtracts the values.
    ///
    /// ```
    ///# use ofws_core::data::map::Map2d;
    ///# use ofws_core::data::map::generation::attributes::generator::GeneratorStep;
    ///# use ofws_core::data::map::generation::step::GenerationStep;
    ///# use ofws_core::data::math::generator::generator2d::Generator2d::IndexGenerator;
    ///# use ofws_core::data::math::size2d::Size2d;
    /// let size = Size2d::new(2, 3);
    /// let mut map = Map2d::new(size);
    /// let attribute_id = map.create_attribute("elevation", 40).unwrap();
    /// let generator = IndexGenerator(size);
    /// let step = GeneratorStep::new("test", attribute_id, generator);
    ///
    /// step.sub(&mut map);
    ///
    /// let attribute = map.get_attribute(attribute_id);
    /// assert_eq!(attribute.get_all(), &vec![40u8, 39, 38, 37, 36, 35]);
    /// ```
    pub fn sub(&self, map: &mut Map2d) {
        info!(
            "Subtract '{}' from attribute '{}' of map '{}'",
            self.name,
            map.get_attribute(self.attribute_id).get_name(),
            map.get_name()
        );

        let size = map.size;
        let attribute = map.get_attribute_mut(self.attribute_id);
        let mut index = 0;

        for y in 0..size.height() {
            for x in 0..size.width() {
                let value = self.generator.generate(x, y);
                let sum = attribute.get(index).saturating_sub(value);
                *attribute.get_mut(index) = sum;
                index += 1;
            }
        }
    }
}

/// For serializing, deserializing & validating [`GeneratorStep`].
///
///```
///# use ofws_core::data::map::generation::attributes::generator::{GeneratorStepData, GeneratorStep};
///# use ofws_core::data::math::generator::generator2d::Generator2dData;
///# use ofws_core::data::math::size2d::Size2d;
///# use std::convert::TryInto;
/// let generator = Generator2dData::IndexGenerator(Size2d::new(1, 2));
/// let data = GeneratorStepData::new("step".to_string(), "attribute".to_string(), generator);
/// let attributes = vec!["attribute".to_string()];
/// let step: GeneratorStep = data.clone().try_convert(&attributes).unwrap();
/// let result: GeneratorStepData = step.convert(&attributes);
/// assert_eq!(data, result)
///```
#[derive(new, Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub struct GeneratorStepData {
    name: String,
    attribute: String,
    generator: Generator2dData,
}

impl GeneratorStepData {
    pub fn try_convert(self, attributes: &[String]) -> Result<GeneratorStep, GenerationStepError> {
        let id = get_attribute_id(&self.attribute, attributes)?;
        let generator: Generator2d = self.generator.try_into()?;
        Ok(GeneratorStep::new(self.name, id, generator))
    }
}

impl GeneratorStep {
    pub fn convert(&self, attributes: &[String]) -> GeneratorStepData {
        let attribute = attributes[self.attribute_id].clone();
        GeneratorStepData::new(self.name.clone(), attribute, (&self.generator).into())
    }
}
